---
- name: deployear java, tomcat y la aplicación
  hosts: redhat
  user: sysadmin
  become: yes
  vars:
    app_dir: /opt/tomcat/webapps
    config_dir: /opt/config
    tomcat_version: 9.0.91 #checkear última versión disponible de tomcat
    tomcat_version_splitted: "{{ tomcat_version.split('.') }}"
    tomcat_major_version: "{{ tomcat_version_splitted[0] }}"
    ansible_python_interpreter: auto_silent

  tasks:

  - name: Actualizar SO para distribución de familia Red Hat
    ansible.builtin.dnf:
      name: '*'
      state: latest
    when: ansible_os_family=='RedHat'

  - name: Actualizar SO para distribución de familia Debian
    ansible.builtin.apt:
      name: '*'
      state: latest
    when: ansible_os_family=='Debian'

  - name: Instalar jdk de java en distribuciones Red Hat
    ansible.builtin.dnf:
      name: java
      state: latest
    when: ansible_os_family=='RedHat'

  - name: instalar jdk de java en distribuciones Debian
    ansible.builtin.apt:
      name: default-jre, default-jdk
      state: latest
    when: ansible_os_family=='Debian'
     
  - name: Crear usuario para Tomcat
    ansible.builtin.user:
      name: tomcat
      shell: /sbin/nologin
      create_home: false

  - name: Checkear que no exista el archivo de instalación de tomcat
    ansible.builtin.stat:
      path: /tmp/apache-tomcat-{{tomcat_version}}.tar.gz
    register: file

  - name: Descargar paquete de instalación de Tomcat desde el repositorio original
    ansible.builtin.get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-{{tomcat_major_version}}/v{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.tar.gz
      dest: /tmp
    when: file.stat.exists == false

  - name: Instalar comandos para extraer el archivo
    ansible.builtin.dnf:
      name: tar
      state: latest

  - name: Checkear que no exista la carpeta donde van los archivos de instalación
    ansible.builtin.stat:
      path: /opt/tomcat
    register: tomcat

  - name: Crea la carpeta si no existe
    ansible.builtin.file:
      path: /opt/tomcat
      state: directory
    when: tomcat.stat.exists==false  
  
  - name: Descomprimir el paquete descargado
    ansible.builtin.unarchive:
      src: /tmp/apache-tomcat-{{tomcat_version}}.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: ['--strip-components=1',]
  
  - name: Cambiar permisos de la carpeta de Tomcat
    ansible.builtin.file:
      path: /opt/tomcat
      state: directory
      recurse: true
      owner: tomcat
      group: tomcat
      mode: '755'
     
  - name: Copiar archivo de configuracion plantilla tomcat.service para Systemd
    ansible.builtin.copy:
      src: ./files/tomcat.service
      dest: /etc/systemd/system/

  - name: Crear carpeta de tomcat que alojará el archivo de configuración de mi aplicación
    ansible.builtin.file:
      path: '{{config_dir}}'
      state: directory

  - name: Copiar archivo de configuración a la carpeta
    ansible.builtin.copy:
      src: ./files/app.properties
      dest: '{{config_dir}}'

  - name: Copiar app todo.war desde el controlador al servidor con tomcat
    ansible.builtin.copy:
      src: ./files/todo.war
      dest: '{{app_dir}}'

  - name: Habilitar e iniciar servicio Tomcat
    ansible.builtin.systemd_service:
      name: tomcat
      state: restarted
      daemon_reload: true
      enabled: true

  - name: Habilitar tráfico a través del puerto 8080 tomcat
    ansible.posix.firewalld:
      port: 8080/tcp
      permanent: true
      state: enabled

  - name: Recargar el firewall
    ansible.builtin.systemd_service:
      name: firewalld
      state: reloaded

...