---
- name: instalar mysql y configurar base de datos
  hosts: ubuntu
  user: sysadmin
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.12

  tasks:
  - name: Actualizar SO para distribución de familia Red Hat
    ansible.builtin.dnf:
      name: '*'
      state: latest
    when: ansible_os_family=='RedHat'
  
  - name: Actualizar SO para distribución de familia Debian
    ansible.builtin.apt:
      name: '*'
      state: latest
    when: ansible_os_family=='Debian'

  - name: instalar mysql service
    ansible.builtin.apt:
      name: mariadb-server
      state: latest

  - name: Asegurar el servicio Mariadb con mysql_secure_installation
    ansible.builtin.expect:
      command: mysql_secure_installation
      responses:
        'Enter current password for root (enter for none)': ""
        'Switch to unix_socket authentication [Y/n]': 'n'
        'Set root password? [Y/n]': 'n'
        'Remove anonymous users? [Y/n]': 'y'
        'Disallow root login remotely? [Y/n]': 'y'
        'Remove test database? [Y/n]': 'y'
        'Reload privilege tables now? [Y/n]': 'y'
      timeout: 1
    register: secure_mariadb
    failed_when: "'... Failed!' in secure_mariadb.stdout_lines"

  - name: Instalar Python y pip
    ansible.builtin.apt:
      name: python3, python3-pip
      state: latest
  
  - name: Instalar módulo requerido para ejecutar SQL queries
    ansible.builtin.pip:
      name: python3-mysqlclient
      state: latest
  
  - name: Crear base de datos todo
    community.mysql.mysql_db:
      name: todo
      state: present
  
  - name: Ejecutar queries SQL requeridas
    community.mysql.mysql_query:
      login_db: todo
      query: 
      - CREATE TABLE `users` ( `id` int(3) NOT NULL AUTO_INCREMENT, `first_name` varchar(20) DEFAULT NULL, `last_name` varchar(20) DEFAULT NULL, `username` varchar(250) DEFAULT NULL, `password` varchar(20) DEFAULT NULL, PRIMARY KEY (`id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
      - CREATE TABLE `todos` ( `id` bigint(20) NOT NULL AUTO_INCREMENT, `description` varchar(255) DEFAULT NULL, `is_done` bit(1) NOT NULL, `target_date` datetime(6) DEFAULT NULL, `username` varchar(255) DEFAULT NULL, `title` varchar(255) DEFAULT NULL, PRIMARY KEY (`id`) ) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci 
      - CREATE USER 'prueba'@'%'' IDENTIFIED BY 'prueba2024' 
      - GRANT ALL PRIVILEGES ON todo.* TO 'todo'@'%' 
      - FLUSH PRIVILEGES
  
  - name: Habilitar tráfico a través del puerto 3306 de MariaDB
    ansible.posix.firewalld:
      port: 3306/tcp
      permanent: true
      state: enabled

  - name: Recargar el firewall
    ansible.builtin.systemd_service:
      name: firewalld
      state: reloaded
...

