---
- name: deployear java, tomcat y la aplicación
  hosts: redhat
  user: sysadmin
  become: yes
  vars:
    app_dir: /opt/tomcat/webapps
    config_dir: /opt/config

  tasks:

  - name: Actualizar SO para distribución de familia Red Hat
    ansible.builtin.dnf:
      name: '*'
      state: latest
    when: ansible_os_family=='RedHat'

  - name: Actualizar SO para distribución de familia Debian
    ansible.builtin.apt:
      name: '*'
      state: latest
    when: ansible_os_family=='Debian'

  - name: instalar jdk de java en distribuciones Red Hat
    ansible.builtin.dnf:
      name: java
      state: latest
    when: ansible_os_family=='RedHat'

  - name: instalar jdk de java en distribuciones Debian
    ansible.builtin.apt:
      name: default-jre, default-jdk
      state: latest
    when: ansible_os_family=='Debian'
  
  - name: Crear usuario para tomcat
    ansible.builtin.user:
      name: tomcat
      shell: /sbin/nologin
      create_home: false

  - name: checkear que no exista el archivo de instalación de tomcat
    ansible.builtin.stat:
      path: /tmp/apache-tomcat-9.0.91.tar.gz
    register: file

  - name: descargar paquete de tomcat desde el repositorio original
    ansible.builtin.get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.91/bin/apache-tomcat-9.0.91.tar.gz
      dest: /tmp
    when: file.stat.exists == false

  - name: Instalar comandos para extraer el archivo
    ansible.builtin.yum:
      name: tar
      state: latest

  - name: checkear que no exista la carpeta
    ansible.builtin.stat:
      path: /opt/tomcat
    register: tomcat

  - name: Crea la carpeta si no existe
    ansible.builtin.file:
      path: /opt/tomcat
      state: directory
    when: tomcat.stat.exists==false  
  
  - name: descomprimir el paquete descargado
    ansible.builtin.unarchive:
      src: '/tmp/apache-tomcat-9.0.91.tar.gz'
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: ['--strip-components=1',]
  
  - name: Cambiar permisos de la carpeta de tomcat
    ansible.builtin.file:
      path: /opt/tomcat
      state: directory
      recurse: true
      owner: tomcat
      group: tomcat
      mode: '755'
     
  - name: copiar archivo de configuracion plantilla tomcat.service
    ansible.builtin.copy:
      src: /home/ansible/obligatorio/tomcat.service
      dest: /etc/systemd/system/

  - name: crear carpeta de tomcat que alojará el archivo de configuración de mi aplicación
    ansible.builtin.file:
      path: '{{config_dir}}'
      state: directory

  - name: copiar archivo de configuración a la carpeta
    ansible.builtin.copy:
      src: /home/ansible/obligatorio/app.properties
      dest: '{{config_dir}}'

  - name: copiar app todo.war desde el controlador al servidor con tomcat
    ansible.builtin.copy:
      src: /home/ansible/obligatorio/todo.war
      dest: '{{app_dir}}'

  - name: Habilitar e iniciar servicio Tomcat
    ansible.builtin.systemd_service:
      name: tomcat
      state: started
      daemon_reload: true
      enabled: true

  - name: Habilitar tráfico a través del puerto 8080 tomcat
    ansible.posix.firewalld:
      port: 8080/tcp
      permanent: true
      state: enabled

  - name: Recargar el firewall
    ansible.builtin.systemd_service:
      name: firewalld
      state: reloaded

...