---
- name: deployear java, tomcat y la aplicación
  hosts: redhat
  user: sysadmin
  become: yes
  vars:
    app_dir: /usr/local/tomcat/webapps
    config_dir: /opt/config
    dir: /home/sysadmin/tomcat

  tasks:

  - name: instalar jdk de java
    ansible.builtin.dnf:
      name: java-1.8.0-openjdk
      state: latest

  - name: instalar tomcat and tools
    ansible.builtin.yum:
      name: tomcat, tomcat-webapps, tomcat-admin-webapps, tomcat-docs-webapp

  - name: crear carpeta de tomcat que alojará el archivo de configuración de mi aplicación
    ansible.builtin.file:
      path: '{{config_dir}}'
      state: directory

  - name: copiar archivo de configuración a la carpeta
    ansible.builtin.copy:
      src: /home/ansible/obligatorio/app.properties
      dest: '{{config_dir}}'

#  - name: copiar app todo.war desde el controlador al servidor con tomcat
#    ansible.builtin.copy:
#      src: /home/ansible/obligatorio/todo.war
#      dest: '{{app_dir}}'

  - name: Habilitar e iniciar servicio Tomcat
    ansible.builtin.systemd_service:
      name: tomcat.service
      state: started
      daemon_reload: true
      enabled: true

  - name: Habilitar tráfico a través del puerto 8080 tomcat
    ansible.posix.firewalld:
      port: 8080/tcp
      permanent: true
      state: enabled

  - name: Recargar el firewall
    ansible.builtin.systemd_service:
      name: firewalld
      state: reloaded

...